### ISSUE TITLE
[T1] Duda sobre procesar imagenes en go

### ISSUE THREAD

**Issue by v4rgas** [IIC2523/syllabus-2023#11]
En GO, deberia convertir la imagen en una matriz, hacer los calculos y luego volverla a hacer imagen o existe una manera distinta de cambiar los valores? puedo editar directamente lo que entrega el jpeg.Decode?

**Comment by tocococa** [comment]
Hola @v4rgas, puedes hacer lo que quieras mientras luego puedas paralelizar el trabajo y entregues el resultado esperado.
