### ISSUE TITLE
[T1] Duda sobre las banderas en la ejecución del programa

### ISSUE THREAD

**Issue by OscarCampohermoso** [IIC2523/syllabus-2023#12]
¿Es correcto entender que si marcamos una bandera como obligatoria usando argparse en Python y flag en Go, el programa no debería ejecutarse si dichas banderas no se proporcionan? y ¿Estoy en lo correcto al utilizar argparse para Python y flag para Go para gestionar estos argumentos?

**Comment by tocococa** [comment]
Hola @OscarCampohermoso, el comportamiento si no se entregan los argumentos queda a tu criterio, puedes defaultear a algún valor o tirar un error. Sobre las librerías, si te funciona bien no hay problema.
