### ISSUE TITLE
[T1] número de thread incluye main thread?

### ISSUE THREAD

**Issue by ignaciomansuy** [IIC2523/syllabus-2023#13]
Hola! Quiero saber si corremos el progama con `-t 3`, debo crear 2 goroutines o 3 goroutines? Es decir el main thread cuenta como uno de los threads pedidos?

**Comment by tocococa** [comment]
Hola @ignaciomansuy, da un poco lo mismo la verdad, pero ese número no debería considerar el thread principal.
