### ISSUE TITLE
[T1] Velocidad de ejecucion Python v/s GO

### ISSUE THREAD

**Issue by Huasito-Appel** [IIC2523/syllabus-2023#17]
Hola! tengo un problemilla con la tarea. Resulta que en python utilice librerias, en particular [convolve2d](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.convolve2d.html) y [numpy](https://numpy.org/) lo que hace que las operaciones matriciales sobre la matriz de la imagen sean extremadamente eficientes, mucho mas eficientes que con multiples go routines en mi implementacion en go, entonces me caigo con lo que pide la pauta en la parte de Rapidez. Queria saber si justifico esto en el Readme lo puedo dejar asi y optar a tener ese punto o debo modificar mi codigo en python para que sea mas ineficiente.  
Dejo como ref los tiempos para una imagen de 11,116KB
Tiempo en GO : 
![image](https://github.com/IIC2523/syllabus-2023/assets/62345634/26a46356-fbdc-4e27-9cdb-4cfd610fdee1)
Tiempo en Python : 
![image](https://github.com/IIC2523/syllabus-2023/assets/62345634/9e4db1db-f7dd-4ac6-abad-358b7b7e4ffe)

Quedo atento a la opcion de dejarlo asi o la necesidad de cambiar mi codigo de python para que sea "mas penca"

**Comment by tocococa** [comment]
Hola @Huasito-Appel, en el enunciado les pedimos que la solución en Python sea single threaded, ojo con las funciones de numpy y convolve2d que estés usando, porque hay varias que son multithreaded.

**Comment by Huasito-Appel** [comment]
Entiedo @tocococa , chequie y si bien no usan en particular las funciones de la lib si lo hacen x detras. ( ya que tienen  BLAS/MKL ) 
sin embargo se puede forzar el single thread en estas lib poniendo un par de variables de entorno, es suficiente esto?

**Comment by tocococa** [comment]
Si cumple con las condiciones del enunciado o por lo menos se ve que lo intentaste está bien.
