### ISSUE TITLE
[T1] Formato de las imágenes

### ISSUE THREAD

**Issue by DanielaCorral** [IIC2523/syllabus-2023#18]
Hola! Quería saber si podemos asumir que las imagenes que usarán para probar nuestras tareas serán solo PNGs o solo JPGs o no podemos asumir eso? Gracias!

**Comment by fbarrosalcalde** [comment]
Me sumo a la pregunta! Debería funcionar con cualquier formato?

**Comment by tocococa** [comment]
Hola @DanielaCorral, no es relevante mientras dejen indicado que formato están trabajando.
