### ISSUE TITLE
[T1] Fecha de entrega

### ISSUE THREAD

**Issue by crisasm01** [IIC2523/syllabus-2023#2]
Hola!

No me queda claro la fecha de entrega de la Tarea 1- Al inicio del enunciado aparece que se entrega el día 9 de septiembre, mientras que en el `README` de este repositorio aparece que se entrega el 1 de septiembre. Cuál es la fecha definitiva de entrega?

Gracias de antemano!

**Comment by tocococa** [comment]
Hola, es para el 1, está corregido.
