### ISSUE TITLE
[T2] problema con submodule rand_server

### ISSUE THREAD

**Issue by nicobuzeta** [IIC2523/syllabus-2023#20]
Hola, el error puede ser mío, pero desde Github y localmente, mi repositorio no parece tener el rand_server subido como un submodule. Desde Github y de local, con --recursive, rand_server me aparece como una carpeta normal con un servidor básico de 14 líneas.

![image](https://github.com/IIC2523/syllabus-2023/assets/11426247/6909c510-a092-439a-89d7-64825791b305)

No tengo mucha experiencia con submodules pero el .gitmodules subido parece tener el path equivocado, ya que tiene `path = rand_server` y no `path = go_crawler/rand_server`.

**Comment by tocococa** [comment]
Hola @nicobuzeta, si, parece que hice algo mal al agregar el submódulo al template, voy a ver cómo arreglarlo.
