### ISSUE TITLE
[T2] Crawler: El servidor siempre tendrá el archivo gopher.jpg?

### ISSUE THREAD

**Issue by domingo2000** [IIC2523/syllabus-2023#23]
Mi duda es simple, al correr el comando  `./server -m 0  -d <depth> -n <nodes>` a veces me genera una estructura de archivos que no contiene al `gopher.jpg` mi duda es, es este caso posible?, o podemos asumir que el gopher siempre estará entre los ficheros

**Comment by tocococa** [comment]
Hola @domingo2000, debería estar siempre, mas tarde o mañana parcho el sim del servidor para que no pase.

**Comment by domingo2000** [comment]
@tocococa  dejé una [PR](https://github.com/IIC2523/rand_server/pull/4) en repo del random server con una versión nueva que podría ser más útil para la tarea jeje. Estuve probando con un crawler distribuido que implementé y de esa forma es más fácil realmente dar "distintos tamaños de input" para el árbol. El detalle está en la PR

**Comment by JuanpaBC** [comment]
holaa, a mi todavía me pasa que a veces no me aparece el archivo gopher :(
