### ISSUE TITLE
[T2] Generales bizantinos: Concenso al que llegan las replicas

### ISSUE THREAD

**Issue by domingo2000** [IIC2523/syllabus-2023#24]
En el algoritmo de generales bizantinos planteado, se pide que "lleguen a concenso", pero en el pseudocódigo dado no se entiende bien ¿Cual es el concenso del cual se está hablando?. En el paper de Liskov se entiende que el algoritmo logra realizar las operaciones enviadas por el cliente con un **orden total** y que ese orden total es el concenso que tienen las distintas réplicas, realizando cada operación en ese mismo orden el al menos *f + 1* nodos no traidores. Pero en el pseudocódigo dado no se envian esos números `n` de la secuencia del mensaje. Por ello no entiendo bien que debemos loguear en el output para que en la corrección se entienda que "llegan a concenso". Se me ocurre
1) Que efectivamente el algoritmo termine por las condiciones de que debe haber concenso para que al cliente le lleguen los `f + 1` mensajes que necesita para corroborar que su operación fue realizada en el sistema.
2) Quizá ustedes esperan que hagamos logs o algo extra en las réplicas para mostrar el concenso.

Gracias de antemano

**Comment by tocococa** [comment]
Hola @domingo2000, la idea es que haya consenso y que eso quede claro al terminar la ejecución, tal vez omití demasiados detalles en la implementación del pseudocódigo y podría aclararlo más. Probablemente una combinación de los puntos 1 y 2 sean suficientes. Ojo que también podrías implementar el algoritmo visto en clases o el de Paxos, como sale en la rúbrica.

Al final lo que importa es tener un algoritmo de resistencia a fallas bizantinas y entenderlo.
