### ISSUE TITLE
[T2] Duda sobre la Estructura del Árbol en el Web-Crawler

### ISSUE THREAD

**Issue by OscarCampohermoso** [IIC2523/syllabus-2023#25]
Necesito aclaración sobre la estructura del árbol para el web-crawler, usando el siguiente input:
```
index&{"files":["file00.txt","file10.txt"],"subdirectories":["d1","d2"]}
```
¿Cómo debería estructurarse el árbol basado en esto? tengo dos interpretaciones:
| Interpretación 1 | Interpretación 2 |
|:----------------:|:----------------:|
| ![Imagen 1](https://github.com/IIC2523/syllabus-2023/assets/104600219/7c3fb319-9fe3-4d71-a92c-e5ad099b0476) | ![Imagen 2](https://github.com/IIC2523/syllabus-2023/assets/104600219/c481321d-e96a-45d6-a56b-0e740deb9b28) |

bueno yo me decante por la segunda opción quisiera confirmar si estoy en lo correcto ya que al final salí con un árbol con esta estructura que se acerca bastante a un árbol de direcciones de archivos.

<img width="400" alt="Captura de pantalla 2023-10-13 a la(s) 17 49 08" src="https://github.com/IIC2523/syllabus-2023/assets/104600219/6fb17cf7-02fa-4b26-a47d-9d349eb0c5a1">

**Comment by tocococa** [comment]
Hola @OscarCampohermoso, el árbol es como lo dibujaste en la interpretación 1.

**Comment by OscarCampohermoso** [comment]
Ok, bueno yo encontraba un problema y es que si asumimos que '*cada subdirectorio tiene un único padre*', no se si estoy cometiendo un error o estoy malinterpretando los datos que se generaron pero por ejemplo yo tengo lo siguiente:

```
index&{"files":["file00.txt","file10.txt"],"subdirectories":["d1","d2"]}
d1&{"files":null,"subdirectories":["d2","d3"]}
d2&{"files":["gopher.jpg"],"subdirectories":["d3","d4"]}
```
Si asumimos que solo puede tener un padre esta configuración no debería ser aceptable:
<img width="529" alt="Captura de pantalla 2023-10-13 a la(s) 20 10 37" src="https://github.com/IIC2523/syllabus-2023/assets/104600219/4f1959b5-80eb-4305-a248-cef3e40269d8">

Lo que generaría un caso peor, en el que **gopher.jpg** se repetiría múltiples veces lo que causaría que se contradiga con la premisa '*solo existe un archivo **gopher.jpg***':
<img width="574" alt="Captura de pantalla 2023-10-13 a la(s) 20 10 09" src="https://github.com/IIC2523/syllabus-2023/assets/104600219/793d8af5-4823-41af-8070-3e4221994b01">

Agradezco cualquier clarificación al respecto.

**Comment by tocococa** [comment]
Si, es algo que estaba pasando, pero si haces pull de los cambios del servidor debería dejar de pasar.
