### ISSUE TITLE
[T2][P1] -o

### ISSUE THREAD

**Issue by Huasito-Appel** [IIC2523/syllabus-2023#26]
Hola, no me queda clara la flag -o. Esta es el Resultado en donde debemos encontrar nuestro archivo gopher.jpg, es decir nuestro algorimo de busqueda conoce a priori la respuesta? Creo que ando bien enredado con esta flag por si me lo pueden aclarar, gracias!

**Comment by tocococa** [comment]
Hola @Huasito-Appel, `-o` es para el output del programa, es la ruta de un archivo donde deben escribir la ruta en que encontraron el archivo `gopher.jpg`.

**Comment by Huasito-Appel** [comment]
Hola! gracias x pescar un sab no me lo espere, me quedo claro en que es el path de output solamente.
