### ISSUE TITLE
[T2] Server de correccion

### ISSUE THREAD

**Issue by Huasito-Appel** [IIC2523/syllabus-2023#27]
Hola, le cambie un detalle minimo al server con el uri, queria saber si el server donde se va a ejecutar el codigo va a ser el que se encuentra subido para en lugar de adaptar el server arreglar mi crawler.

**Comment by tocococa** [comment]
Hola @Huasito-Appel, que cambio hiciste?

**Comment by Huasito-Appel** [comment]
esto nomas.
`if len(uri) > 0 && uri[len(uri)-1:] == "/" {`
originalmente estaba.
` if uri[len(uri)-1:] == "/" {`
es por como esta escrito mi crawler nomas.

**Comment by tocococa** [comment]
Haz una PR en el repo del servidor con ese cambio.
