### ISSUE TITLE
[T2] Problema con git clone

### ISSUE THREAD

**Issue by sopadeoliva** [IIC2523/syllabus-2023#28]
Holi, al hacer el git clone --recursive me aparecio este msj:
<img width="1115" alt="Captura de Pantalla 2023-10-14 a la(s) 22 11 13" src="https://github.com/IIC2523/syllabus-2023/assets/42161679/bb6188f3-59f3-44a3-a93d-9f75b3ddfa71">

me ayudan a entender que onda porfavors? 🙃

**Comment by tocococa** [comment]
Hola @sopadeoliva, ese error en general ocurre cuando cambiaste tu llave SSH, lo más fácil es que vayas a tu carpeta .ssh y elimines del archivo `known_hosts` a la llave que sale en la línea 4.

**Comment by sopadeoliva** [comment]
graciaaas

**Comment by tocococa** [comment]
Revisa la issue #29, creo que es el mismo problema.
