### ISSUE TITLE
[T2] Problema clonando el repositorio del servidor

### ISSUE THREAD

**Issue by ignaciovilla** [IIC2523/syllabus-2023#29]
Hola! No he logrado clonar el repositorio del servidor. Probé usando git clone git@github.com:IIC2523/rand_server.git y también clonando recursivamente el repositorio con el template y me aparece el mismo error. Lo copio a continuación:
<img width="866" alt="Captura de pantalla 2023-10-15 173932" src="https://github.com/IIC2523/syllabus-2023/assets/62113032/4ce022ed-a38d-43ad-a1b9-371b5fba5598">

Agradecería cualquier tipo de ayuda. 
Muchas gracias de antemano.

**Comment by tocococa** [comment]
Hola @ignaciovilla, que comando estás usando para clonar tu repo?

**Comment by ignaciovilla** [comment]
Hola, este:
git clone --recursive https://github.com/IIC2523/t2-iic2523-ignaciovilla.git

**Comment by tocococa** [comment]
Hola @ignaciovilla, @JuanpaBC, pueden usar `git clone --recursive git@github.com:IIC2523/<reponame>` para clonar sus tareas? Con eso debería dejar de dar problemas, pero tienen que tener SSH configurado con sus cuentas de GitHub.

**Comment by ignaciovilla** [comment]
Eso me funcionó, muchas gracias!

**Comment by JuanpaBC** [comment]
hola, a mí tmb!
