### ISSUE TITLE
[T1] Librerias recomendas

### ISSUE THREAD

**Issue by v4rgas** [IIC2523/syllabus-2023#3]
Hola, que es lo que recomiendan para poder abrir y cambiar las imagenes? hay alguna libreria externa que se pueda usar para abrir la imagen? (google varias pero no se cual recomeindan)

**Comment by tocococa** [comment]
Hola, no hay muchas restricciones, para Python puedes usar OpenCV, Numpy, etc. y para Go puedes usar Image. Les voy a subir una cápsula explicando manejo básico de línea de comandos, gorutinas e imágenes en Golang de aquí al lunes.

**Comment by v4rgas** [comment]
Muchas gracias!
