### ISSUE TITLE
[T2] Prepare() y Commit()

### ISSUE THREAD

**Issue by Martinrsts** [IIC2523/syllabus-2023#30]
Hola,

En la pregunta de generales bizantinos dicen que debemos implementar el pseudocógigo descrito. No aparece que hace Prepare() o Commit(), me confunde la parte que dice que no necestiamos leer el paper completo. ¿Necesitamos leer algunas partes del paper para poder entender esas funciones?
Tampoco entiendo porque el líder recibe mensajes y después no hace nada con ellos, ¿puede ser que el cliente está haciendo una parte que en verdad es el líder el que debería hacerlo? Me hace sentido también porque en la descripción dice que el líder es el único que se comunica con el cliente, pero en el pseudocódigo las replicas le envían mensajes al cliente.

**Comment by Martinrsts** [comment]
Tampoco entiendo porque el líder recibe mensajes y después no hace nada con ellos, ¿puede ser que el cliente está haciendo una parte que en verdad es el líder el que debería hacerlo? Me hace sentido también porque en la descripción dice que el líder es el único que se comunica con el cliente, pero en el pseudocódigo las replicas le envían mensajes al cliente.

**Comment by tocococa** [comment]
Hola @Martinrsts, el pseudocódigo está para que se hagan una idea de que deben implementar, pueden revisar el paper, slides de clases u otros recursos. El algoritmo que implementen no debe ser 1:1 el del paper mientras resuelvan el problema. Que las réplicas le respondan directo al cliente es un error de redacción, pero funcionalmente no cambia mucho el algoritmo.
