### ISSUE TITLE
[T2] Threads en Crawler

### ISSUE THREAD

**Issue by Martinrsts** [IIC2523/syllabus-2023#32]
hola,

cuando se habla de número de threads, el programa principal vale como un thread o solamente son las gorutinas?

**Comment by tocococa** [comment]
Hola @Martinrsts, se refiere al número de gorutinas que deberías usar para explorar el árbol expuesto por el servidor.

**Comment by Martinrsts** [comment]
Ya perfecto.
¿Y se refiere al número de gorutinas a la vez o el total? Si es el número de gorutinas a la vez, ¿Vale una gorutina que está esperando mensajes? Es decir, si el número de threads es 3, ¿es válido que hayan 2 gorutinas detenidas esperando un mensaje mientras otras 3 están haciendo algo?

**Comment by tocococa** [comment]
Puedes tomarlo como el valor de gorutinas ejecutando concurrentemente si lo puedes manejar bien, pero yo te recomendaría invocar sólo a ese número como tope, porque probablemente es más fácil de implementar.
