### ISSUE TITLE
[T2] Tiempo de ejecución promedio en crawler según threads

### ISSUE THREAD

**Issue by festelle** [IIC2523/syllabus-2023#33]
Implementé un algoritmo de random walks para el crawler, y revisé que en promedio es más rápido mientras más threads son usados, pero a veces pasa que el usar 1 thread es más rápido que usar n threads (al revisar de forma aleatoria, puede pasar que justo cuando se use solo un thread encuentre al tiro el archivo).

Esto afectará el puntaje o está bien que en promedio mientras más threads se tenga, más rápido sea? O la idea es que implementemos un algoritmo que definitivamente encuentre más rápido el archivo con más threads?

**Comment by tocococa** [comment]
Hola @festelle, si implementaste un algoritmo de ese estilo probablemente sea difícil de evaluar, la idea es que el algoritmo implementado para un arbol fijo, sea más rápido al ejecutar con varias gorutinas.
