### ISSUE TITLE
[T2] Número de gorutinas "concurrentes"

### ISSUE THREAD

**Issue by CrisBerriosL** [IIC2523/syllabus-2023#34]
Hola!
Tengo una duda de si cuando se habla del número de gorutinas que exploran el árbol de manera concurrente.
Se refiere al máximo total de gorutinas de todo el programa? O solo una máximo para las que se están ejecutando al mismo tiempo?

Por ejemplo, si el máximo es 2, e inicializo dos gorutinas, en el caso que una de las dos termine, puedo ejecutar una tercera gorutina? Considerando que siempre hay un máximo de 2 ejecutándose al mismo tiempo

**Comment by tocococa** [comment]
Hola @CrisBerriosL, revisa la issue #32
