### ISSUE TITLE
Criterio Rapidez

### ISSUE THREAD

**Issue by Martinrsts** [IIC2523/syllabus-2023#35]
Hola,
Para el criterio de rapidez para el crawler es solamente la comparación entre un thread y dos threads? Porque mi programa mejora bastante a partir de tres threads, pero después empieza a empeorar. Creo que depende un poco de la topología del árbol de directorios.

**Comment by Huasito-Appel** [comment]
me sumo a la pregunta

**Comment by tocococa** [comment]
Hola @Martinrsts, sería esperable que con 3 rutinas igual sea mejor que con solo una sola rutina, pero dependiendo de la implementación podría variar. Lo importante es que sea más rápido que con una sola rutina.
