### ISSUE TITLE
[T2] Duda output Parte 1

### ISSUE THREAD

**Issue by fbarrosalcalde** [IIC2523/syllabus-2023#36]
Hola! El output debe ser como aparece en el enunciado, por ejemplo: /index/d1/d2/d34/d45/gopher.jpg? O puede ser la ruta completa, por ejemplo: http://localhost:8080/index/d1/d2/d34/d45/gopher.jpg?

**Comment by tocococa** [comment]
Hola @fbarrosalcalde, da un poco lo mismo mientras sea la ruta correcta.
