### ISSUE TITLE
[T2] P2 - Atacar o retirarse

### ISSUE THREAD

**Issue by ignaciomansuy** [IIC2523/syllabus-2023#37]
Hola! Quiero confirmar lo siguiente:
1) ¿la decisión de atacar o retirarse es aleatoria (50/50) para todos los nodos no? (independiente de si están healty o failing) 
2) Si un nodo está failing, entonces la decisión de conscenso a la que llega no tiene porqué ser la misma a la que llegan los nodos healty no? Esto va en relación a que nos piden imprimir la decisión a la que ha llegado cada nodo.

**Comment by tocococa** [comment]
Hola @ignaciomansuy, tu puedes decidir si tus generales parten de acuerdo o no y cual es el plan de cada uno, lo que importa es el resultado final y la implementación. La decisión a la que llega el nodo que esta fallando no es relevante.
