### ISSUE TITLE
[T2] Dudas varias sobre el algoritmo práctico de Generales Bizantinos

### ISSUE THREAD

**Issue by DanielaCorral** [IIC2523/syllabus-2023#38]
Hola! He intentado entender el algoritmo PBFT de Liskov hace varios días pero aún me quedan algunas dudas:
1. El PBFT en general es utilizado en contextos de consistencia para replicación de bdd, por lo que me imagino que no se espera que los nodos del algoritmo que quieren que programemos se pongan de acuerdo en atacar o defender. Por eso me gustaría consultar qué tipo de estructura esperan que tengan los requests del cliente y la estructura de los mensajes (¿qué se están enviando los nodos entre ellos?). Sería ideal si me dieran un ejemplo concreto y completo del funcionamiento que ustedes esperan, como "teniendo X request del cliente en una red con 4 nodos y un traidor, se esperaría que los nodos hagan Y y lleguen a la decisión Z".
2.  En general sabemos que las réplicas faulty quieren enviar a la red mensajes maliciosos para confundir. Sin embargo, en el contexto del algoritmo PBFT no me queda tan claro qué mensajes pueden ser esos para confundir a la red. Honestamente le pregunté a chatGPT al respecto (no encontré nada en internet) y decía que las réplicas bizantinas pueden mandar mensajes de PREPARE o COMMIT con requests distintos a los del cliente a las otras réplicas, pero eso nuevamente me genera la duda 1 porque desconozco la naturaleza de los requests del cliente
3. No me queda claro al leer el paper ni el pseudocódigo qué pasa si una réplica que todavía no termina de recibir mensajes de tipo PREPARE de las otras réplicas recibe un mensaje de tipo COMMIT de otra. ¿Se pierde? ¿Lo deja esperando y lo recibe cuando empiece a recibir de tipo COMMIT?

De antemano muchas gracias por cualquier orientación

**Comment by OscarCampohermoso** [comment]
Me uno a la consulta anterior. Además, me surge una inquietud con respecto al resultado final que se espera del algoritmo PBFT. Por lo que entendí en clase, esperaría que proporcionáramos valores aleatorios 'A' y 'R' y que llegáramos a un consenso basándonos en el algoritmo. Sin embargo, en base a lo discutido, siento que el algoritmo de dos ruedas podría ser más apropiado para este contexto. ¿Podrían aclararnos cuál es el output deseado para esta sección?

**Comment by tocococa** [comment]
Hola @DanielaCorral, @OscarCampohermoso, en el punto 1, la estructura es la que estimes necesaria ustedes para poder ejecutar el algoritmo y mostrar que es resistente a fallas bizantinas. Sobre el punto 2, las réplicas pueden mandar mensajes con información errónea o inconsistente en el paso en que se comunican todas entre ellas, que contienen esos mensajes depende de lo que hayas definido respecto al punto 1. Si recibe un mensaje de commit antes de recibir todos los prepare, lo razonable sería que lo dejara encolado hasta recibir los commits necesarios que aún no le han llegado. Sobre la última pregunta, podrían usar el algoritmo de dos ruedas si creen que es más fácil/razonable/adecuado de implementar, mientras indiquen si hicieron algo diferente.

**Comment by DanielaCorral** [comment]
A partir de lo que me dices me quedo un poco donde mismo 😞  , en especial porque lo único que hemos visto en clases son los mensajes tipo "atacar" y "retirada" en un contexto más teórico y el algoritmo de PBFT (práctico) no usa ese tipo de mensajes como tengo entendido y no he podido encontrar algún ejemplo de ejecución en internet. Entiendo que la implementación es libre, pero dado que el enunciado no dice nada al respecto no me queda claro cómo evaluarán la correctitud de nuestra P2, cómo evaluarán que los nodos bizantinos realmente intenten confundir a los nodos, etc. O dicho de otra forma, cómo nosotros quedar tranquilos con que nuestra sol es correcta si no hay ningún formato para lo que los nodos deben ponerse de acuerdo

De todas formas, ahora me surge la duda de que si decidiéramos ocupar el algoritmo de 2 ruedas como dices tú, ese solo sirve para cuando tienes 1 traidor bizantino, y no un número variable como dicen en el enunciado. Por ello, pregunto para confirmar: si quisiéramos implementarlo deberíamos generalizarlo para n traidores? Considerando que el problema de los generales bizantinos tiene un enfoque más teórico y que por ello hay papers con soluciones prácticas como el PBFT

**Comment by tocococa** [comment]
@DanielaCorral, puedes aprovechar el algoritmo PBFT como una forma de llegar a consenso sobre si se debe o no llegar a un acuerdo, en este caso, el commit a la DB que traba de PBFT podría ser la decisión de atacar o defender, y depende del estado de las replicas si estan disponibles o no para hacer el commit. Si implementas correctamente un algoritmo de consenso con tolerancia a fallas Bizantinas la evaluación va a ser positiva, la rubrica es amplia justamente para darles flexibilidad en eso.

Sip, deberían extenderlo, el algoritmo visto en clases es extensible a `n` generales con hasta `n/3 - 1` traidores, que es el límite de traidores que se indica en el enunciado, así que no debería haber problema con eso, a medida que aumenta el numero de traidores lo único que hay que hacer es repetir las ruedas, que es un problema en entornos reales por la cantidad de mensajes que se generan, pero para el caso de la tarea no es relevante.
