### ISSUE TITLE
[T2]: Duda sobre formato de los path del servidor en web crawler

### ISSUE THREAD

**Issue by tcouso** [IIC2523/syllabus-2023#39]
Hola, 

Se puede asumir que los path del server que van a usar para testar van a ser del formato "http://localhost:8080/index"? En la pauta daban como ejemplo algo del formato "http://localhost:8080", pero ahí habría que agregar el index a mano después, y encuentro que es medio feo. Quedo atento, saludos!

**Comment by tocococa** [comment]
Hola @tcouso, la idea es que el flag `-a` sea solo la dirección donde va a correr el servidor.
