### ISSUE TITLE
[T1] Aplicación del Kernel

### ISSUE THREAD

**Issue by juanelsch** [IIC2523/syllabus-2023#4]
Hola!
Tengo una duda respeto a como se aplica el kernel. Si bien en la capsula se transforma cada pixel a un número que representa su escala de grises, me puse a investigar en internet y explican que para una imagen a color, el kernel se le debe aplicar a cada  canal de color (rojo, verde y azul). Quería saber si es que para esta tarea hay que aplicar el kernel a la escala de grises solamente o a los tres canales.

**Comment by tocococa** [comment]
Hola @juanelsch, cualquiera de las dos estrategias sirve, si lo aplicas a la imagen en escala de grises después no cuesta mucho extenderlo para tres canales, pero mientras el resultado sea el esperado no importa mucho si lo haces en escala de grises o RGB.
