### ISSUE TITLE
[T3] Duda sobre implementacion

### ISSUE THREAD

**Issue by v4rgas** [IIC2523/syllabus-2023#41]
Como deberiamos hacer para que los filosofos sepan cuales son las ips con las que se pueden comunicar para el left/right?

Se debe decidir esto de manera automatica o puede ser una variable de entorno hardcodeada para cada contenedor?

**Comment by tocococa** [comment]
Hola @v4rgas, mientras funciones bien pueden hacer un poco lo que quieran, pueden dejarlo hardcodeado si les es más fácil.
