### ISSUE TITLE
[T3] Modo de enviar y recibir mensajes

### ISSUE THREAD

**Issue by Martinrsts** [IIC2523/syllabus-2023#42]
Hola,

¿Cómo se deben enviar y recibir los mensajes a través de máquinas con distinta dirección IP?

**Comment by tocococa** [comment]
Hola @Martinrsts, para comunicar equipos con diferentes direcciones IP en la misma subred, puedes usar el paquete [`net`](https://pkg.go.dev/golang.org/x/net#section-readme).

Si quieres parsear una dirección IP en texto plano, puedes usar `formatted_addr, err := net.ResolveTCPAddr("tcp", addr)` y así verificar que sirva, aunque también se puede pasar la dirección directamente como un string.

Para escuchar a una conexión TCP, puedes usar lo siguiente:
```go
laddr, err := net.ResolveTCPAddr("tcp", addr)
l, err := net.ListenTCP("tcp", laddr)  // abre un listener TCP en la direccion indicada
if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
defer l.Close()
conn, err := l.AcceptTCP() // espera y acepta una nueva conexion, conn es un *net.TCPConn
if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
buf := make([]byte, 1024)

n, err := conn.Read(buf)  // lee un mensaje desde la conexion a un buffer de bytes
if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
fmt.Println(string(n[:]))
conn.Close()
```
Para manejar más conexiones, bastaría que coloques el `conn, err := l.AcceptTCP()` en un loop y luego pases `conn` a una gorutina que maneje la conexión.

Para conectarte a otro equipo y enviar un mensaje, podrías hacer algo como lo siguiente:
````go
raddr, err := net.ResolveTCPAddr("tcp", addr)
if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
conn, err := net.DialTCP("tcp", nil, raddr) // intenta conectarse a la direccion entregada
defer conn.Close()
text := "Hello World!"
_, err = conn.Write([]byte(text))  // escribe un mensaje en bytes a la conexion
if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
```
