### ISSUE TITLE
[T3] Respuesta Wireguard

### ISSUE THREAD

**Issue by yuwet15** [IIC2523/syllabus-2023#43]
Hola, queria saber cuanto tardaría en obtener los datos (la dirección IP del servidor VPN, su rango de IPs, dirección
IP para el cliente y la llave pública del servidor) una vez completado el form.

Gracias de antemano

**Comment by tocococa** [comment]
Hola @yuwet15, voy a tratar de revisar las solicitudes todos los días alrededor de esta hora, salvo los fines de semana deberían estar en menos de un día.
