### ISSUE TITLE
[T3] Duda sobre implementación Server Cliente

### ISSUE THREAD

**Issue by yuwet15** [IIC2523/syllabus-2023#44]
Hola, en el enunciado no se especifica, pero podría implementarlo utilizando un servidor y 5 clientes(filosofos)?.

**Comment by tocococa** [comment]
Hola @yuwet15, la idea es que no usen un servidor.

**Comment by yuwet15** [comment]
bueno gracias

**Comment by CrisBerris** [comment]
Podemos usar un servidor para que se conecten los filósofos inicialmente, y una vez estén todos conectados el servidor les envíe la info necesaria, se apague y los filósofos funcionen por su cuenta?

**Comment by CrisBerriosL** [comment]
Podemos usar un servidor para que se conecten los filósofos inicialmente, y una vez estén todos conectados el servidor les envíe la info necesaria, se apague y los filósofos funcionen por su cuenta?

**Comment by tocococa** [comment]
Hola @CrisBerriosL, podrías, pero probablemente es más fácil que definas un archivo de configuración con todos esos parámetros para cada filósofo.
