### ISSUE TITLE
[T3] Duda elección algortimo visto en clases

### ISSUE THREAD

**Issue by fbarrosalcalde** [IIC2523/syllabus-2023#46]
Hola! Quería saber si podemos implementar el algoritmo de la diapositiva 37 en vez del que se recomienda en el enunciado. Vi las restricciones del enunciado y las cumple.

**Comment by fbarrosalcalde** [comment]
También tengo la duda de si elegir ese algoritmo generaría problemas al implementar el archivo de docker?

**Comment by tocococa** [comment]
Hola @fbarrosalcalde, no, porque el algoritmo que aparece antes de la slide 38 puede producir espera circular.

No se a que te refieres con implementar el archivo de docker, te refieres al docker compose?

**Comment by fbarrosalcalde** [comment]
Pero el algortimo de la diapo 37 si evita la espera circular, porque lo que hace es que el quinto filósofo toma primero el tenedor derecho y luego el izquierdo, en cambio, los otros 4 primero toman el tenedor izquierdo y luego el derecho. Adjunto foto del algortimo al que me refiero.
![IMG_2852](https://github.com/IIC2523/syllabus-2023/assets/53537582/723a2fe3-61d4-4030-9589-ef96435c6e20)

Respecto a lo del archivo docker, si me refiero al docker compose.

**Comment by fbarrosalcalde** [comment]
Mi pregunta va a si es posible implementar ese algortimo, porque el otro se ve harto más complejo jaja

**Comment by fbarrosalcalde** [comment]
Quedo atento, gracias!

**Comment by tocococa** [comment]
@fbarrosalcalde cómo sabes que cubierto es el de la derecha y cuál es el de la izquierda en el caso de implementar el algoritmo de manera distribuida? En parte por eso tiene que implementar la versión con meseros.

**Comment by fbarrosalcalde** [comment]
Porque el arreglo de semáforos son los tenedores, entonces de ahí le asigno a cada filósofo su tenedor izquierdo y el derecho (según los índices del arreglo y el id del filósofo).

**Comment by fbarrosalcalde** [comment]
Ya lo programé y me funcionó, por eso quería saber. En el caso en que no se pueda, para intentar con el otro.

**Comment by fbarrosalcalde** [comment]
El problema yo creo puede darse al hacer el docker compose, porque hay una variable compartida que sería el arreglo, pero no estoy seguro.

**Comment by fbarrosalcalde** [comment]
Oka gracias, intentaré con el otro.
