### ISSUE TITLE
[T3]: Duda Archivo de Logs y Terminación de la Ejecución

### ISSUE THREAD

**Issue by domingo2000** [IIC2523/syllabus-2023#47]
Hola tengo dos dudas
1) ¿El archivo de logs podría simplemente ser una redirección de los logs de docker-compose? Ya que compose junta los logs de los distintos contenedores asi que tirando logs en STDOUT queda todo bastante ordenado y fácil para leer en la corrección, creo que redirigir esos logs a un archivo es una solución buena. onda `docker compose up > logs.txt`

2) Debe terminar el algoritmo luego de que todos los filósofos coman o puede quedar ejecutando hasta que llegue alguna interrupción. Pregunto pues en el caso en que deba terminar el algoritmo se debe asegurar que todos hayan comido, que se pasen los tenedores mientras no todos hayan terminado etcetera, por lo que requiere de un algoritmo de terminación distribuido. La otra opción es esperar en los logs que todos coman y enviarle una interrupción al programa.

Espero su respuesta gracias!

**Comment by tocococa** [comment]
Hola @domingo2000, mientras el archivo con los logs tenga toda la información necesaria no hay problema, sobre la segunda pregunta, la idea sería que el algoritmo termine una vez que todos hayan comido n veces, cómo acaba no es relevante mientras termine.
