### ISSUE TITLE
[T3] Duda uso de Dockers en meseros

### ISSUE THREAD

**Issue by juanelsch** [IIC2523/syllabus-2023#48]
Entiendo según el enunciado que se debe tener en cada contenedor a un filosofo con su código respectivo, pero que sucede con los meseros? estos también deberían estar junto con el filósofo dentro del contenedor o estos deben ir en un archivo main.go por ejemplo? en donde tenga a todos los meseros.

**Comment by tocococa** [comment]
Hola @juanelsch, vas a hacerlo en grupo con WireGuard o individualmente con Docker? En cualquier caso lo ideal sería que el mesero acompañara al filósofo.

**Comment by jpsanchez7** [comment]
Hola! Yo lo que hice fue tener 10 contenedores, 5 para los filósofos y 5 para los meseros. Esta bien esto? 😢
