### ISSUE TITLE
[T3] Duda de conexiones a traves de wireguard

### ISSUE THREAD

**Issue by iananwandter** [IIC2523/syllabus-2023#49]
Logramos conectarnos al servidor de wireguard pero no podemos enviar ni recibir paquetes entre nosotros. Intentamos con ping y tambien con algo semejante a la issue #42 . ¿Hay algo que estemos haciendo mal o haya que hacer algo que no este en las instrucciones del setup de wireguard?

**Comment by tocococa** [comment]
Hola @iananwandter, lo reviso en un rato, puede que se me haya desconfigurado algo a mi o me haya faltado algo en la guia del setup, cuando llamas a `wg`  que te aparece?

**Comment by iananwandter** [comment]
La verdad estamos haciendolo a traves de windows con la app de wireguard, ya que con wsl da un error que para solucionarlo se tiene que descargar el codigo fuente de wsl y cambiar algunos parametros y recompilar todo.

**Comment by tocococa** [comment]
Okay, era un tema mio con la configuración de wireguard en el servidor, por favor me avisan si ahora pueden ver sus maquinas, yo acabo de probar con dos pcs mios esta funcionando. Voy a dejar andando `10.20.4.2` que tiene ICMP activado, prueben pingueando a esa dirección, si no les funciona puede que sea algo raro con el cliente de wireguard para windows.

**Comment by iananwandter** [comment]
Todo bien ahora, probe tanto por ICMP y TCP. Muchas gracias

**Comment by IgnaciaJ** [comment]
Hola! nosotras estamos con el mismo problema

**Comment by IgnaciaJ** [comment]
Tampoco nos funciona hacer el ping al 10.20.4.2
cree otro tunnel y volví a llenar el form, en caso de que ese sea el problema

**Comment by tocococa** [comment]
Hola @IgnaciaJ, que no hayas podido hacer ping a `10.20.4.2` es normal porque ese computador estaba apagado. Sobre tu conexión, acabo de ver que había ingresado mal tus datos en la configuración del servidor, ahora si debería estar funcionando.

**Comment by VAKELA** [comment]
Hola @tocococa, yo estoy teniendo un problema similar tambien. Ahora pude hacer ping a `10.20.4.2`, pero no puedo conectarme a mi compañero. Estamos probando con ping y con el codigo que pusiste en un issue, pero nada funciona.

**Comment by IgnaciaJ** [comment]
Hola @tocococa! volvi a intentar y aún no me está funcionando, no puedo realizar ping con mi compañera y al momento que corro sudo wg, me arroja lo siguiente:

<img width="630" alt="image" src="https://github.com/IIC2523/syllabus-2023/assets/69643709/d6b465dd-2e34-4d3b-b613-9feb19964436">

**Comment by maureencooper** [comment]
> Hola @IgnaciaJ, que no hayas podido hacer ping a `10.20.4.2` es normal porque ese computador estaba apagado. Sobre tu conexión, acabo de ver que había ingresado mal tus datos en la configuración del servidor, ahora si debería estar funcionando.

Hola @tocococa!! Nos funcionó un rato con @IgnaciaJ , los Ping y todo, pero ahora de la nada nos dejó de funcionar... Qué puede ser?

**Comment by jpvergaralb** [comment]
Estamos teniendo los mismos problemas con mi compañera 😢

**Comment by Emiliax16** [comment]
lo mismo con mi compañero, nos funcionó el ping hace un par de días pero ahora nada. Con sudo wg aparece todo como en la guía, pero no nos hemos podido conectar de nuevo

**Comment by tocococa** [comment]
@VAKELA quién es tu compañero? A ti si te veo conectada correctamente.

**Comment by tocococa** [comment]
@maureencooper si no me das mas información sobre tu configuración o que están intentando hacer no te puedo ayudar mucho, pero a ti te veo como ultima vez conectada hace 13 horas y a tu compañera hace 9.

**Comment by tocococa** [comment]
@Emiliax16 quién es tu compañero? A mi me apareces como ultima vez conectada hace 4 horas

**Comment by jacorderoluco** [comment]
> @VAKELA quién es tu compañero? A ti si te veo conectada correctamente. Si no puedes pinguear a tu compañero puede que tenga ICMP desactivado.

@tocococa yo soy el compañero.

**Comment by tocococa** [comment]
@jacorderoluco me aparece que te conectaste por ultima vez hace 14 horas, has intentado conectarte hoy?

**Comment by jacorderoluco** [comment]
> @jacorderoluco me aparece que te conectaste por ultima vez hace 14 horas, has intentado conectarte hoy?

Hola, puedo ejecutar wg y hacerte ping al 10.20.4.2, pero nunca a mi compañero. Me conecto sin problemas.

**Comment by Emiliax16** [comment]
> @Emiliax16 quién es tu compañero? A mi me apareces como ultima vez conectada hace 4 horas

lo probamos de nuevo y nos resultó correr el programa en ambos computadores, aunque yo sigo sin poder hacer ping ni el servidor  ni a mi compañero (a pesar de estar conectada y poder correr la tarea). No hay problema con esto?

**Comment by tocococa** [comment]
Hola @Emiliax16, si les resultó eso no hay problema. Que no puedan hacer ping entre ustedes puede ser porque tienen ICMP desactivado.

@Ignacio321, @jacorderoluco prueben correr el programa entre ambos computadores nomás, si se logran conectar está bien.

**Comment by ferperezh** [comment]
hola yo con mi compañero @kipasten tratamos de hacer un ping entre nosotros tambien falla pero si estamos conectados al servidor
que puede ser?

**Comment by ferperezh** [comment]
<img width="409" alt="Captura de pantalla 2023-11-21 a la(s) 19 22 35" src="https://github.com/IIC2523/syllabus-2023/assets/69528837/3c4fa9a4-4f40-47a8-a193-b2ae838cdf02">
Esta es la foto de wg

**Comment by tocococa** [comment]
@ferperezh supongo que es porque había rellenado con otra llave pública en el form.

**Comment by ferperezh** [comment]
si justo era por eso pero me pregunta ahora con esto ya listo el nacho que es window puede hacer ping a mi compu pero yo no al de el que soy mac

**Comment by tocococa** [comment]
@ferperezh el ping puede que funcione o no, pero igual deberían poder conectarse entre ustedes
