### ISSUE TITLE
[T3] Problema Iniciar tunel wireguard.

### ISSUE THREAD

**Issue by mpenalozag** [IIC2523/syllabus-2023#50]
Hola, al intentar iniciar el servidor con "sudo wg-quick up wg", luego de realizar la configuración, me sale el siguiente error. No sé que estoy haciendo mal

![image](https://github.com/IIC2523/syllabus-2023/assets/62019954/4d87c0d7-c990-4429-98d2-fc29f869b1ec)

Gracias de antemano por la ayuda!

**Comment by mpenalozag** [comment]
Al final ese error, era porque estaba desde otro dispositivo, distinto al que use para rellenar el formulario. De todas maneras, intentando desde el dispositivo correcto me sale el siguiente error.

![imagen](https://github.com/IIC2523/syllabus-2023/assets/62019954/2b7091e0-7767-4b5d-8a1c-96c5f42df35c)

**Comment by tocococa** [comment]
Hola @mpenalozag, puedes mostrarme como es tu archivo `wg0.conf`?

**Comment by mpenalozag** [comment]
Ahi va

![imagen](https://github.com/IIC2523/syllabus-2023/assets/62019954/290c0957-7e83-4c57-905c-c4463b77a010)

**Comment by tocococa** [comment]
@mpenalozag NO subas tu llave privada

**Comment by mpenalozag** [comment]
oh se me fue. 
![imagen](https://github.com/IIC2523/syllabus-2023/assets/62019954/0d13df56-87a0-4a68-86c0-5b79cbda7d1a)

**Comment by tocococa** [comment]
Creo que es [un problema con WSL2](https://unix.stackexchange.com/questions/700620/run-wireguard-as-a-client-on-win10-with-wsl2), tendrías que usar el cliente WireGuard de windows o bootear a Linux.

**Comment by mpenalozag** [comment]
ya perfecto, muchas gracias! y para la llave privada puedo usar la misma?

**Comment by tocococa** [comment]
Prueba con las mismas, yo ahora voy a salir, así que si las llegas a tener que regenerar, más en la noche podría volver a agregar tu llave nueva al VPN.

**Comment by mpenalozag** [comment]
Ahi meti las mismas llaves al cliente de Windows pero no se bien como comprobar que esta funcionando.

**Comment by tocococa** [comment]
@mpenalozag revisa la issue #49

**Comment by mpenalozag** [comment]
Hola! Ahi pude configurar WireGuard pero no logra hacer los handshakes correctamente.

![imagen](https://github.com/IIC2523/syllabus-2023/assets/62019954/8f6ab019-2754-4a7d-bb08-06d9e9e06b66)

**Comment by tocococa** [comment]
@mpenalozag tu respondiste el formulario dos veces, cuál de las dos llaves que mandaste estás tratando de usar?

**Comment by mpenalozag** [comment]
La primera que mande es la que estoy tratando de usar. Ayer respondi el form de nuevo para ver si con otra key funciona.

**Comment by tocococa** [comment]
No veo que te hayas conectado en los logs del servidor, cómo tienes configurada la conexión?

**Comment by mpenalozag** [comment]
aca va la config que estoy usando

![imagen](https://github.com/IIC2523/syllabus-2023/assets/62019954/0f022a4e-2ff7-455b-a78c-441860c1d0cc)

**Comment by mpenalozag** [comment]
He probado de todo, y no se que pueda estar pasando. Lo unico que nos falta con mi pareja es esta conexion a wireguard.

**Comment by tocococa** [comment]
@mpenalozag tu llave pública está mal, en el form mandaste  `RvYtHbDXJ8nKbwDIXtXQhcfEgtn9LFiswWb/pbowPQI=`

**Comment by mpenalozag** [comment]
La primera llave publica, que sale abajo del nombre, es autogenerada. La 2da llave publica, que sale abajo de [Peer] es la llave publica del servidor que me llego al mail.

**Comment by mpenalozag** [comment]
Probe cambiandola y no me resulta, no se si estare haciendo algo mal

**Comment by mpenalozag** [comment]
Ah creo que entiendo el problema. Efectivamente, tengo una key diferente. Puedo mandarte el form de nuevo por ultima vez para probar de nuevo?
