### ISSUE TITLE
Pauta I1

### ISSUE THREAD

**Issue by fbarrosalcalde** [IIC2523/syllabus-2023#51]
Hola! Pueden subir la pauta de la Interrogación 1 porfa, muchas gracias.

**Comment by tocococa** [comment]
Hola @fbarrosalcalde, voy a preguntarle al profesor.

**Comment by fbarrosalcalde** [comment]
Entra toda la materia para el examen?

**Comment by tocococa** [comment]
Hola @fbarrosalcalde, confirma con el profesor eso. La pauta de la i1 debería estar hoy en la tarde.

**Comment by tocococa** [comment]
@fbarrosalcalde está en Canvas la pauta de la I1.
