### ISSUE TITLE
[T3] Uso de meseros

### ISSUE THREAD

**Issue by maureencooper** [IIC2523/syllabus-2023#52]
Hola! Respecto a la similitud de nuestro algoritmo con el de la slide 38 de la clase, qué tan parecidos deben ser? Específicamente, si estamos haciendo la tarea en parejas, es necesario implementar meseros?

**Comment by tocococa** [comment]
Hola @maureencooper, si, son parte del algoritmo.

**Comment by Ignacio321** [comment]
Entonces si uno tiene una solución que funciona, pero sin meseros, está mal?

**Comment by tocococa** [comment]
@Ignacio321 si no hay nada que cumpla el rol de los meseros tendrías menos puntaje en la sección del algoritmo.
