### ISSUE TITLE
[T3] Terminación con Filósofos y Meseros en Docker

### ISSUE THREAD

**Issue by OscarCampohermoso** [IIC2523/syllabus-2023#54]
Hola, mi configuración para resolver la tarea incluye 10 contenedores: 5 para filósofos y 5 para meseros. Los filósofos terminan correctamente, pero me enfrento a un problema con la terminación de los meseros. Como los filósofos no terminan al mismo tiempo, los meseros continúan en ejecución para asegurar que los filósofos puedan comer n veces.

Para resolver esto, estoy considerando un servidor centralizado que coordine la terminación. Los filósofos notificarían a este servidor cuando terminen, y una vez que todos hayan terminado, el servidor indicaría a los meseros que finalicen.

Mi pregunta es: ¿Es adecuado usar un servidor de coordinación centralizado para este propósito en un sistema distribuido, o debería emplear un algoritmo distribuido de terminación para mantener una solución descentralizada? ¿Qué enfoque sería más apropiado para garantizar una terminación ordenada en este entorno?

Agradecería cualquier consejo o sugerencia.

**Comment by tocococa** [comment]
Hola @OscarCampohermoso, la idea es que sea un algoritmo distribuido, por lo que no deberías usar ese servidor centralizado.
