### ISSUE TITLE
[T1] Resultado Esperado imagenes.

### ISSUE THREAD

**Issue by Huasito-Appel** [IIC2523/syllabus-2023#6]
Hola! Por lo que entendi del resultado el tipo de kernel, ya sea uno tipico o "custom" que utilicemos no sera evaluado, por lo que la imagen que generemos de output, por muy "fea" que salga no tiene insidencia en la evaluacion.
A modo de referencia estoy trabajando con esta 255x255 original :
![image](https://github.com/IIC2523/syllabus-2023/assets/62345634/812e41a6-bedf-4d7a-b015-c02f763c3520)
Y estos estan siendo mis resultados.
![image](https://github.com/IIC2523/syllabus-2023/assets/62345634/3f092bae-961e-4e19-843c-8bcbce623cab)![image](https://github.com/IIC2523/syllabus-2023/assets/62345634/64370481-7050-4ca1-9242-7d8c4d2eb733)
![image](https://github.com/IIC2523/syllabus-2023/assets/62345634/e013237a-cf06-45cb-8de5-5fdeb81efb0f)

Para mis distintos kernells. Quiero confirmar que el tipo de kernell de uso es irrelevante, Gracias!

**Comment by tocococa** [comment]
Hola @Huasito-Appel, a priori los kernels dan un poco lo mismo, pero en el enunciado se mencionan 3 de 3x3 que son bien conocidos.

**Comment by jpvergaralb** [comment]
> Hola @Huasito-Appel, a priori los kernels dan un poco lo mismo, pero en el enunciado se mencionan 3 de 3x3 que son bien conocidos.
> 
> Lo que si NO deberías hacer, es reducir la resolución de la imagen de input.

con no reducir la resolucion de la img del input te refieres a que tanto la img resultante de aplicar el kernel como la img original deben tener la misma resolucion?
