### ISSUE TITLE
[T1] Duda con respecto a cantidad de subrutinas

### ISSUE THREAD

**Issue by ignaciovilla** [IIC2523/syllabus-2023#7]
Hola! Tengo una duda con respecto a esta sección del enunciado:
"Además, su solución en Go debe permitir seleccionar el número de gorutinas que usará para aplicar la convolución"
Con respecto a esto, nosotros tenemos que decidir en donde usaremos las gorutinas?
Hay algún límite de gorutinas que pueden ser seleccionadas?
Muchas gracias de antemano

**Comment by tocococa** [comment]
Hola @ignaciovilla no hay límite sobre la cantidad de gorutinas, la idea es que experimenten un poco con rangos, y del problema propuesto debería poder ver en que parte es conveniente ocupar gorutinas.
