### ISSUE TITLE
[T1] Precisión de las imagenes

### ISSUE THREAD

**Issue by juanelsch** [IIC2523/syllabus-2023#8]
Hola!
Tengo la duda de como evaluaran la precisión de las imágenes. Al utilizar la función que retorna los valores RGBA de un pixel los retorna como un uint32 mientras que la función que recibe los valores RGBA para setear un pixel en una nueva imagen lo hace a traves de uint8. Se que existen métodos para hacer la conversión, sin embargo, al comparar los pixeles (sin aplicar transformación, solo copiando la imagen a un nuevo archivo) se nota que hay pixeles distintos.

**Comment by tocococa** [comment]
Hola @juanelsch, no te preocupes por eso, no es le foco de la tarea. Mientras se pueda ver bien el resultado no hay problema.
