### ISSUE TITLE
Path relativo o absoluto

### ISSUE THREAD

**Issue by Martinrsts** [IIC2523/syllabus-2023#9]
Hola,

Los paths de input y output para la tarea deben ser relativos o absolutos?

**Comment by tocococa** [comment]
Hola @Martinrsts, deberían ser relativos.

**Comment by Martinrsts** [comment]
Ya perfecto! Y se puede asumir que el path va a ser del estilo "path.jpeg"? Osea que use comillas y tenga la extensión del archivo?
